dotnet clean C:\git\MonitoringCore\Core\Core.sln
rmdir /S /Q "C:\git\MonitoringCore\Core\Core\bin"
rmdir /S /Q "C:\git\MonitoringCore\Core\Core\obj"
rmdir /S /Q "C:\git\MonitoringCore\Core\CoreService\bin"
rmdir /S /Q "C:\git\MonitoringCore\Core\CoreService\obj"
rmdir /S /Q "C:\git\MonitoringCore\Core\Sharp7Interface\bin"
rmdir /S /Q "C:\git\MonitoringCore\Core\Sharp7Interface\obj"
rmdir /S /Q "C:\git\MonitoringCore\Core\BACnetInterface\bin"
rmdir /S /Q "C:\git\MonitoringCore\Core\BACnetInterface\obj"
rmdir /S /Q "C:\git\MonitoringCore\Core\Contracts\bin"
rmdir /S /Q "C:\git\MonitoringCore\Core\Contracts\obj"
rmdir /S /Q "C:\git\MonitoringCore\Core\RabbitInterface\bin"
rmdir /S /Q "C:\git\MonitoringCore\Core\RabbitInterface\obj"
rmdir /S /Q "C:\git\MonitoringCore\Core\JobsService\bin"
rmdir /S /Q "C:\git\MonitoringCore\Core\JobsService\obj"