// <auto-generated />
using System;
using Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Core.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241112083929_db0009")]
    partial class db0009
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Models.ActiveAlarm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AlarmId")
                        .HasColumnType("uuid")
                        .HasColumnName("alarm_id");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<long>("Time")
                        .HasColumnType("bigint")
                        .HasColumnName("time");

                    b.HasKey("Id");

                    b.HasIndex("AlarmId");

                    b.HasIndex("ItemId");

                    b.HasIndex("ItemId", "AlarmId");

                    b.ToTable("active_alarms");
                });

            modelBuilder.Entity("Core.Models.Alarm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("AlarmDelay")
                        .HasColumnType("integer")
                        .HasColumnName("alarm_delay");

                    b.Property<int>("AlarmPriority")
                        .HasColumnType("integer")
                        .HasColumnName("alarm_priority");

                    b.Property<int>("AlarmType")
                        .HasColumnType("integer")
                        .HasColumnName("alarm_type");

                    b.Property<int>("CompareType")
                        .HasColumnType("integer")
                        .HasColumnName("compare_type");

                    b.Property<bool>("IsDisabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_disabled");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<int?>("Timeout")
                        .HasColumnType("integer")
                        .HasColumnName("timeout");

                    b.Property<string>("Value1")
                        .HasColumnType("text")
                        .HasColumnName("value1");

                    b.Property<string>("Value2")
                        .HasColumnType("text")
                        .HasColumnName("value2");

                    b.HasKey("Id");

                    b.ToTable("alarms");
                });

            modelBuilder.Entity("Core.Models.AlarmAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("ActionType")
                        .HasColumnType("integer")
                        .HasColumnName("action_type");

                    b.Property<Guid>("AlarmId")
                        .HasColumnType("uuid")
                        .HasColumnName("alarm_id");

                    b.Property<Guid?>("ControllerId")
                        .HasColumnType("uuid")
                        .HasColumnName("controller_id");

                    b.Property<string>("ControllerValue")
                        .HasColumnType("text")
                        .HasColumnName("controller_value");

                    b.Property<string>("MemoryAddress")
                        .HasColumnType("text")
                        .HasColumnName("memory_address");

                    b.Property<bool>("TriggerOn")
                        .HasColumnType("boolean")
                        .HasColumnName("trigger_on");

                    b.HasKey("Id");

                    b.ToTable("alarm_actions");
                });

            modelBuilder.Entity("Core.Models.AlarmHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(0)
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<long>("Time")
                        .HasColumnType("bigint")
                        .HasColumnName("time")
                        .HasColumnOrder(1);

                    b.Property<Guid>("AlarmId")
                        .HasColumnType("uuid")
                        .HasColumnName("alarm_id");

                    b.Property<string>("AlarmLog")
                        .HasColumnType("text")
                        .HasColumnName("alarm_log");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.HasKey("Id", "Time");

                    b.HasIndex("AlarmId");

                    b.HasIndex("ItemId");

                    b.HasIndex("Time");

                    b.HasIndex("ItemId", "Time");

                    b.ToTable("alarm_history");
                });

            modelBuilder.Entity("Core.Models.ControllerSharp7", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("DBAddress")
                        .HasColumnType("integer")
                        .HasColumnName("db_address");

                    b.Property<int>("DBSizeData")
                        .HasColumnType("integer")
                        .HasColumnName("db_size_data");

                    b.Property<int>("DBStartData")
                        .HasColumnType("integer")
                        .HasColumnName("db_start_data");

                    b.Property<int>("DataType")
                        .HasColumnType("integer")
                        .HasColumnName("data_type");

                    b.Property<byte[]>("EncryptedPassword")
                        .HasColumnType("bytea")
                        .HasColumnName("encrypted_password");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<bool?>("IsDisabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_disabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("controller_sharp7");
                });

            modelBuilder.Entity("Core.Models.Dictionary", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.ToTable("dictionary");
                });

            modelBuilder.Entity("Core.Models.FinalItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<long>("Time")
                        .HasColumnType("bigint")
                        .HasColumnName("time");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("ItemId")
                        .IsUnique();

                    b.ToTable("final_items");
                });

            modelBuilder.Entity("Core.Models.ItemHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(0)
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<long>("Time")
                        .HasColumnType("bigint")
                        .HasColumnName("time")
                        .HasColumnOrder(1);

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id", "Time");

                    b.HasIndex("ItemId");

                    b.HasIndex("Time");

                    b.HasIndex("ItemId", "Time");

                    b.ToTable("items_history");
                });

            modelBuilder.Entity("Core.Models.MapSharp7", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int?>("Bit")
                        .HasColumnType("integer");

                    b.Property<Guid>("ControllerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("map_sharp7");
                });

            modelBuilder.Entity("Core.Models.MonitoringItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("CalculationMethod")
                        .HasColumnType("integer")
                        .HasColumnName("calculation_method");

                    b.Property<bool?>("IsDisabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_disabled");

                    b.Property<string>("ItemName")
                        .HasColumnType("text")
                        .HasColumnName("item_name");

                    b.Property<int>("ItemType")
                        .HasColumnType("integer")
                        .HasColumnName("item_type");

                    b.Property<float>("NormMax")
                        .HasColumnType("real")
                        .HasColumnName("norm_max");

                    b.Property<float>("NormMin")
                        .HasColumnType("real")
                        .HasColumnName("norm_min");

                    b.Property<int>("NumberOfSamples")
                        .HasColumnType("integer")
                        .HasColumnName("number_of_samples");

                    b.Property<string>("OffText")
                        .HasColumnType("text")
                        .HasColumnName("off_text");

                    b.Property<string>("OnText")
                        .HasColumnType("text")
                        .HasColumnName("on_text");

                    b.Property<int>("PointNumber")
                        .HasColumnType("integer")
                        .HasColumnName("point_number");

                    b.Property<int>("SaveHistoricalInterval")
                        .HasColumnType("integer")
                        .HasColumnName("save_historical_interval");

                    b.Property<int>("SaveInterval")
                        .HasColumnType("integer")
                        .HasColumnName("save_interval");

                    b.Property<int>("SaveOnChange")
                        .HasColumnType("integer")
                        .HasColumnName("save_on_change");

                    b.Property<float>("SaveOnChangeRange")
                        .HasColumnType("real")
                        .HasColumnName("save_on_change_range");

                    b.Property<float>("ScaleMax")
                        .HasColumnType("real")
                        .HasColumnName("scale_max");

                    b.Property<float>("ScaleMin")
                        .HasColumnType("real")
                        .HasColumnName("scale_min");

                    b.Property<int>("ShouldScale")
                        .HasColumnType("integer")
                        .HasColumnName("should_scale");

                    b.Property<string>("Unit")
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.HasKey("Id");

                    b.ToTable("items");
                });

            modelBuilder.Entity("Core.Models.RawItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<long>("Time")
                        .HasColumnType("bigint")
                        .HasColumnName("time");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.ToTable("raw_items");
                });
#pragma warning restore 612, 618
        }
    }
}
