// <auto-generated />
using System;
using Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Core.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251231051925_AddDeadbandMemory")]
    partial class AddDeadbandMemory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Models.ActiveAlarm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AlarmId")
                        .HasColumnType("uuid")
                        .HasColumnName("alarm_id");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<long>("Time")
                        .HasColumnType("bigint")
                        .HasColumnName("time");

                    b.HasKey("Id");

                    b.HasIndex("AlarmId");

                    b.HasIndex("ItemId");

                    b.HasIndex("ItemId", "AlarmId");

                    b.ToTable("active_alarms");
                });

            modelBuilder.Entity("Core.Models.Alarm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("AlarmDelay")
                        .HasColumnType("integer")
                        .HasColumnName("alarm_delay");

                    b.Property<int>("AlarmPriority")
                        .HasColumnType("integer")
                        .HasColumnName("alarm_priority");

                    b.Property<int>("AlarmType")
                        .HasColumnType("integer")
                        .HasColumnName("alarm_type");

                    b.Property<int>("CompareType")
                        .HasColumnType("integer")
                        .HasColumnName("compare_type");

                    b.Property<bool?>("HasExternalAlarm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("has_external_alarm");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsDisabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_disabled");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("MessageFa")
                        .HasColumnType("text")
                        .HasColumnName("message_fa");

                    b.Property<int?>("Timeout")
                        .HasColumnType("integer")
                        .HasColumnName("timeout");

                    b.Property<string>("Value1")
                        .HasColumnType("text")
                        .HasColumnName("value1");

                    b.Property<string>("Value2")
                        .HasColumnType("text")
                        .HasColumnName("value2");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("alarms");
                });

            modelBuilder.Entity("Core.Models.AlarmHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(0)
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<long>("Time")
                        .HasColumnType("bigint")
                        .HasColumnName("time")
                        .HasColumnOrder(1);

                    b.Property<Guid>("AlarmId")
                        .HasColumnType("uuid")
                        .HasColumnName("alarm_id");

                    b.Property<string>("AlarmLog")
                        .HasColumnType("text")
                        .HasColumnName("alarm_log");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.HasKey("Id", "Time");

                    b.HasIndex("AlarmId");

                    b.HasIndex("ItemId");

                    b.HasIndex("Time");

                    b.HasIndex("ItemId", "Time");

                    b.ToTable("alarm_history");
                });

            modelBuilder.Entity("Core.Models.AverageMemory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("EnableOutlierDetection")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("enable_outlier_detection");

                    b.Property<bool>("IgnoreStale")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ignore_stale");

                    b.Property<string>("InputItemIds")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("input_item_ids");

                    b.Property<int>("Interval")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10)
                        .HasColumnName("interval");

                    b.Property<bool>("IsDisabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_disabled");

                    b.Property<int>("MinimumInputs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("minimum_inputs");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("OutlierMethod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("outlier_method");

                    b.Property<double>("OutlierThreshold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(1.5)
                        .HasColumnName("outlier_threshold");

                    b.Property<Guid>("OutputItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("output_item_id");

                    b.Property<long>("StaleTimeout")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(60L)
                        .HasColumnName("stale_timeout");

                    b.Property<string>("Weights")
                        .HasColumnType("text")
                        .HasColumnName("weights");

                    b.HasKey("Id");

                    b.ToTable("average_memory");
                });

            modelBuilder.Entity("Core.Models.ComparisonMemory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ComparisonGroups")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("comparison_groups");

                    b.Property<int>("GroupOperator")
                        .HasColumnType("integer")
                        .HasColumnName("group_operator");

                    b.Property<int>("Interval")
                        .HasColumnType("integer")
                        .HasColumnName("interval");

                    b.Property<bool>("InvertOutput")
                        .HasColumnType("boolean")
                        .HasColumnName("invert_output");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_disabled");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OutputItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("output_item_id");

                    b.HasKey("Id");

                    b.ToTable("comparison_memory");
                });

            modelBuilder.Entity("Core.Models.ControllerBACnet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("DeviceId")
                        .HasColumnType("integer")
                        .HasColumnName("device_id");

                    b.Property<bool?>("IsDisabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_disabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("controller_bacnet");
                });

            modelBuilder.Entity("Core.Models.ControllerModbus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int?>("AddressBase")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("address_base");

                    b.Property<int?>("ConnectionType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("connection_type");

                    b.Property<int>("DataLength")
                        .HasColumnType("integer")
                        .HasColumnName("data_length");

                    b.Property<int>("DataType")
                        .HasColumnType("integer")
                        .HasColumnName("modbus_datatype");

                    b.Property<int?>("Endianness")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("endianness");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<bool?>("IsDisabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_disabled");

                    b.Property<int?>("ModbusType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("modbus_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Port")
                        .HasColumnType("integer")
                        .HasColumnName("port");

                    b.Property<int>("StartAddress")
                        .HasColumnType("integer")
                        .HasColumnName("start_address");

                    b.Property<byte?>("UnitIdentifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)1)
                        .HasColumnName("unit_identifier");

                    b.HasKey("Id");

                    b.ToTable("controller_modbus");
                });

            modelBuilder.Entity("Core.Models.ControllerSharp7", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("DBAddress")
                        .HasColumnType("integer")
                        .HasColumnName("db_address");

                    b.Property<int>("DBSizeData")
                        .HasColumnType("integer")
                        .HasColumnName("db_size_data");

                    b.Property<int>("DBStartData")
                        .HasColumnType("integer")
                        .HasColumnName("db_start_data");

                    b.Property<int>("DataType")
                        .HasColumnType("integer")
                        .HasColumnName("data_type");

                    b.Property<byte[]>("EncryptedPassword")
                        .HasColumnType("bytea")
                        .HasColumnName("encrypted_password");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<bool?>("IsDisabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_disabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("controller_sharp7");
                });

            modelBuilder.Entity("Core.Models.DeadbandMemory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<double>("Deadband")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0)
                        .HasColumnName("deadband");

                    b.Property<int>("DeadbandType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("deadband_type");

                    b.Property<Guid>("InputItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("input_item_id");

                    b.Property<double>("InputMax")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(100.0)
                        .HasColumnName("input_max");

                    b.Property<double>("InputMin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0)
                        .HasColumnName("input_min");

                    b.Property<int>("Interval")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("interval");

                    b.Property<bool>("IsDisabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_disabled");

                    b.Property<long?>("LastChangeTime")
                        .HasColumnType("bigint")
                        .HasColumnName("last_change_time");

                    b.Property<double?>("LastInputValue")
                        .HasColumnType("double precision")
                        .HasColumnName("last_input_value");

                    b.Property<double?>("LastOutputValue")
                        .HasColumnType("double precision")
                        .HasColumnName("last_output_value");

                    b.Property<long?>("LastTimestamp")
                        .HasColumnType("bigint")
                        .HasColumnName("last_timestamp");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OutputItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("output_item_id");

                    b.Property<bool?>("PendingDigitalState")
                        .HasColumnType("boolean")
                        .HasColumnName("pending_digital_state");

                    b.Property<double>("StabilityTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(1.0)
                        .HasColumnName("stability_time");

                    b.HasKey("Id");

                    b.ToTable("deadband_memory");
                });

            modelBuilder.Entity("Core.Models.Dictionary", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.ToTable("dictionary");
                });

            modelBuilder.Entity("Core.Models.ExternalAlarm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AlarmId")
                        .HasColumnType("uuid")
                        .HasColumnName("alarm_id");

                    b.Property<bool>("IsDisabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_disabled");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<bool>("Value")
                        .HasColumnType("boolean")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("AlarmId");

                    b.ToTable("external_alarms");
                });

            modelBuilder.Entity("Core.Models.FinalItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<long>("Time")
                        .HasColumnType("bigint")
                        .HasColumnName("time");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("ItemId")
                        .IsUnique();

                    b.ToTable("final_items");
                });

            modelBuilder.Entity("Core.Models.FormulaMemory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("DecimalPlaces")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2)
                        .HasColumnName("decimal_places");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Expression")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("expression");

                    b.Property<string>("ExpressionHash")
                        .HasColumnType("text")
                        .HasColumnName("expression_hash");

                    b.Property<int>("Interval")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10)
                        .HasColumnName("interval");

                    b.Property<bool>("IsDisabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_disabled");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<long?>("LastEvaluationTime")
                        .HasColumnType("bigint")
                        .HasColumnName("last_evaluation_time");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OutputItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("output_item_id");

                    b.Property<string>("Units")
                        .HasColumnType("text")
                        .HasColumnName("units");

                    b.Property<string>("VariableAliases")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("{}")
                        .HasColumnName("variable_aliases");

                    b.HasKey("Id");

                    b.ToTable("formula_memory");
                });

            modelBuilder.Entity("Core.Models.HolidayCalendar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("holiday_calendar");
                });

            modelBuilder.Entity("Core.Models.HolidayDate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<double?>("HolidayAnalogValue")
                        .HasColumnType("double precision")
                        .HasColumnName("holiday_analog_value");

                    b.Property<Guid>("HolidayCalendarId")
                        .HasColumnType("uuid")
                        .HasColumnName("holiday_calendar_id");

                    b.Property<bool?>("HolidayDigitalValue")
                        .HasColumnType("boolean")
                        .HasColumnName("holiday_digital_value");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("HolidayCalendarId", "Date");

                    b.ToTable("holiday_date");
                });

            modelBuilder.Entity("Core.Models.IfMemory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Branches")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("[]")
                        .HasColumnName("branches");

                    b.Property<double>("DefaultValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0)
                        .HasColumnName("default_value");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("Interval")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("interval");

                    b.Property<bool>("IsDisabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_disabled");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OutputItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("output_item_id");

                    b.Property<int>("OutputType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("output_type");

                    b.Property<string>("VariableAliases")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("{}")
                        .HasColumnName("variable_aliases");

                    b.HasKey("Id");

                    b.ToTable("if_memory");
                });

            modelBuilder.Entity("Core.Models.ItemHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(0)
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<long>("Time")
                        .HasColumnType("bigint")
                        .HasColumnName("time")
                        .HasColumnOrder(1);

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id", "Time");

                    b.HasIndex("ItemId");

                    b.HasIndex("Time");

                    b.HasIndex("ItemId", "Time");

                    b.ToTable("items_history");
                });

            modelBuilder.Entity("Core.Models.MapBACnet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ControllerId")
                        .HasColumnType("uuid")
                        .HasColumnName("controller_id");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<int>("ObjectId")
                        .HasColumnType("integer")
                        .HasColumnName("object_id");

                    b.Property<int>("ObjectType")
                        .HasColumnType("integer")
                        .HasColumnName("object_type");

                    b.Property<int?>("OperationType")
                        .HasColumnType("integer")
                        .HasColumnName("io_operation_type");

                    b.HasKey("Id");

                    b.ToTable("map_bacnet");
                });

            modelBuilder.Entity("Core.Models.MapModbus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ControllerId")
                        .HasColumnType("uuid")
                        .HasColumnName("controller_id");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<int?>("OperationType")
                        .HasColumnType("integer")
                        .HasColumnName("io_operation_type");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.HasKey("Id");

                    b.ToTable("map_modbus");
                });

            modelBuilder.Entity("Core.Models.MapSharp7", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int?>("Bit")
                        .HasColumnType("integer")
                        .HasColumnName("bit");

                    b.Property<Guid>("ControllerId")
                        .HasColumnType("uuid")
                        .HasColumnName("controller_id");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<int?>("OperationType")
                        .HasColumnType("integer")
                        .HasColumnName("io_operation_type");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.HasKey("Id");

                    b.ToTable("map_sharp7");
                });

            modelBuilder.Entity("Core.Models.ModbusGatewayConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("ConnectedClients")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("connected_clients");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.Property<DateTime?>("LastReadTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_read_time");

                    b.Property<DateTime?>("LastWriteTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_write_time");

                    b.Property<string>("ListenIP")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("0.0.0.0")
                        .HasColumnName("listen_ip");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Port")
                        .HasColumnType("integer")
                        .HasColumnName("port");

                    b.Property<byte>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)1)
                        .HasColumnName("unit_id");

                    b.HasKey("Id");

                    b.HasIndex("Port")
                        .IsUnique();

                    b.ToTable("modbus_gateway_config");
                });

            modelBuilder.Entity("Core.Models.ModbusGatewayMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("DataRepresentation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2)
                        .HasColumnName("data_representation");

                    b.Property<int>("Endianness")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("endianness");

                    b.Property<Guid>("GatewayId")
                        .HasColumnType("uuid")
                        .HasColumnName("gateway_id");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<int>("ModbusAddress")
                        .HasColumnType("integer")
                        .HasColumnName("modbus_address");

                    b.Property<int>("RegisterCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("register_count");

                    b.Property<int>("RegisterType")
                        .HasColumnType("integer")
                        .HasColumnName("register_type");

                    b.Property<float?>("ScaleMax")
                        .HasColumnType("real")
                        .HasColumnName("scale_max");

                    b.Property<float?>("ScaleMin")
                        .HasColumnType("real")
                        .HasColumnName("scale_min");

                    b.HasKey("Id");

                    b.HasIndex("GatewayId");

                    b.HasIndex("ItemId");

                    b.HasIndex("GatewayId", "RegisterType", "ModbusAddress");

                    b.ToTable("modbus_gateway_mapping");
                });

            modelBuilder.Entity("Core.Models.MonitoringItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("CalculationMethod")
                        .HasColumnType("integer")
                        .HasColumnName("calculation_method");

                    b.Property<float?>("CalibrationA")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(1f)
                        .HasColumnName("calibration_a");

                    b.Property<float?>("CalibrationB")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(0f)
                        .HasColumnName("calibration_b");

                    b.Property<int>("InterfaceType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("interface_type");

                    b.Property<bool?>("IsCalibrationEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_calibration_enabled");

                    b.Property<bool?>("IsDisabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_disabled");

                    b.Property<bool>("IsEditable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_editable");

                    b.Property<string>("ItemName")
                        .HasColumnType("text")
                        .HasColumnName("item_name");

                    b.Property<string>("ItemNameFa")
                        .HasColumnType("text")
                        .HasColumnName("item_name_fa");

                    b.Property<int>("ItemType")
                        .HasColumnType("integer")
                        .HasColumnName("item_type");

                    b.Property<float>("NormMax")
                        .HasColumnType("real")
                        .HasColumnName("norm_max");

                    b.Property<float>("NormMin")
                        .HasColumnType("real")
                        .HasColumnName("norm_min");

                    b.Property<int>("NumberOfSamples")
                        .HasColumnType("integer")
                        .HasColumnName("number_of_samples");

                    b.Property<string>("OffText")
                        .HasColumnType("text")
                        .HasColumnName("off_text");

                    b.Property<string>("OffTextFa")
                        .HasColumnType("text")
                        .HasColumnName("off_text_fa");

                    b.Property<string>("OnText")
                        .HasColumnType("text")
                        .HasColumnName("on_text");

                    b.Property<string>("OnTextFa")
                        .HasColumnType("text")
                        .HasColumnName("on_text_fa");

                    b.Property<int>("PointNumber")
                        .HasColumnType("integer")
                        .HasColumnName("point_number");

                    b.Property<int>("SaveHistoricalInterval")
                        .HasColumnType("integer")
                        .HasColumnName("save_historical_interval");

                    b.Property<int>("SaveInterval")
                        .HasColumnType("integer")
                        .HasColumnName("save_interval");

                    b.Property<int>("SaveOnChange")
                        .HasColumnType("integer")
                        .HasColumnName("save_on_change");

                    b.Property<float>("SaveOnChangeRange")
                        .HasColumnType("real")
                        .HasColumnName("save_on_change_range");

                    b.Property<float>("ScaleMax")
                        .HasColumnType("real")
                        .HasColumnName("scale_max");

                    b.Property<float>("ScaleMin")
                        .HasColumnType("real")
                        .HasColumnName("scale_min");

                    b.Property<int>("ShouldScale")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2)
                        .HasColumnName("should_scale");

                    b.Property<string>("Unit")
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.Property<string>("UnitFa")
                        .HasColumnType("text")
                        .HasColumnName("unit_fa");

                    b.HasKey("Id");

                    b.HasIndex("PointNumber")
                        .IsUnique();

                    b.ToTable("items");
                });

            modelBuilder.Entity("Core.Models.PIDMemory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("CascadeLevel")
                        .HasColumnType("integer")
                        .HasColumnName("cascade_level");

                    b.Property<double>("DeadZone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0)
                        .HasColumnName("dead_zone");

                    b.Property<double>("DerivativeFilterAlpha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(1.0)
                        .HasColumnName("derivative_filter_alpha");

                    b.Property<Guid?>("DigitalOutputItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("digital_output_item_id");

                    b.Property<double>("FeedForward")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0)
                        .HasColumnName("feed_forward");

                    b.Property<double>("HysteresisHighThreshold")
                        .HasColumnType("double precision")
                        .HasColumnName("hysteresis_high_threshold");

                    b.Property<double>("HysteresisLowThreshold")
                        .HasColumnType("double precision")
                        .HasColumnName("hysteresis_low_threshold");

                    b.Property<Guid>("InputItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("input_item_id");

                    b.Property<int>("Interval")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10)
                        .HasColumnName("interval");

                    b.Property<bool>("IsAuto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_auto");

                    b.Property<Guid?>("IsAutoId")
                        .HasColumnType("uuid")
                        .HasColumnName("is_auto_id");

                    b.Property<bool>("IsDisabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_disabled");

                    b.Property<double>("Kd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.050000000000000003)
                        .HasColumnName("kd");

                    b.Property<double>("Ki")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.10000000000000001)
                        .HasColumnName("ki");

                    b.Property<double>("Kp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(1.0)
                        .HasColumnName("kp");

                    b.Property<double?>("ManualValue")
                        .HasColumnType("double precision")
                        .HasColumnName("manual_value");

                    b.Property<Guid?>("ManualValueId")
                        .HasColumnType("uuid")
                        .HasColumnName("manual_value_id");

                    b.Property<double>("MaxOutputSlewRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(100.0)
                        .HasColumnName("max_output_slew_rate");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OutputItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("output_item_id");

                    b.Property<double>("OutputMax")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(100.0)
                        .HasColumnName("output_max");

                    b.Property<double>("OutputMin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0)
                        .HasColumnName("output_min");

                    b.Property<Guid?>("ParentPIDId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_pid_id");

                    b.Property<bool>("ReverseOutput")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("reverse_output");

                    b.Property<Guid?>("ReverseOutputId")
                        .HasColumnType("uuid")
                        .HasColumnName("reverse_output_id");

                    b.Property<double?>("SetPoint")
                        .HasColumnType("double precision")
                        .HasColumnName("set_point");

                    b.Property<Guid?>("SetPointId")
                        .HasColumnType("uuid")
                        .HasColumnName("set_point_id");

                    b.HasKey("Id");

                    b.ToTable("pid_memory");
                });

            modelBuilder.Entity("Core.Models.PIDTuningSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double?>("CalculatedKd")
                        .HasColumnType("double precision")
                        .HasColumnName("calculated_kd");

                    b.Property<double?>("CalculatedKi")
                        .HasColumnType("double precision")
                        .HasColumnName("calculated_ki");

                    b.Property<double?>("CalculatedKp")
                        .HasColumnType("double precision")
                        .HasColumnName("calculated_kp");

                    b.Property<double?>("ConfidenceScore")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence_score");

                    b.Property<double?>("CriticalGain")
                        .HasColumnType("double precision")
                        .HasColumnName("critical_gain");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<double>("MaxAmplitude")
                        .HasColumnType("double precision")
                        .HasColumnName("max_amplitude");

                    b.Property<int>("MaxCycles")
                        .HasColumnType("integer")
                        .HasColumnName("max_cycles");

                    b.Property<int>("MinCycles")
                        .HasColumnType("integer")
                        .HasColumnName("min_cycles");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<double>("OriginalKd")
                        .HasColumnType("double precision")
                        .HasColumnName("original_kd");

                    b.Property<double>("OriginalKi")
                        .HasColumnType("double precision")
                        .HasColumnName("original_ki");

                    b.Property<double>("OriginalKp")
                        .HasColumnType("double precision")
                        .HasColumnName("original_kp");

                    b.Property<double?>("OscillationAmplitude")
                        .HasColumnType("double precision")
                        .HasColumnName("oscillation_amplitude");

                    b.Property<Guid>("PIDMemoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("pid_memory_id");

                    b.Property<double>("RelayAmplitude")
                        .HasColumnType("double precision")
                        .HasColumnName("relay_amplitude");

                    b.Property<double>("RelayHysteresis")
                        .HasColumnType("double precision")
                        .HasColumnName("relay_hysteresis");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Timeout")
                        .HasColumnType("integer")
                        .HasColumnName("timeout");

                    b.Property<double?>("UltimatePeriod")
                        .HasColumnType("double precision")
                        .HasColumnName("ultimate_period");

                    b.HasKey("Id");

                    b.ToTable("pid_tuning_session");
                });

            modelBuilder.Entity("Core.Models.RateOfChangeMemory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("AccumulatedSamples")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("accumulated_samples");

                    b.Property<Guid?>("AlarmOutputItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("alarm_output_item_id");

                    b.Property<bool?>("AlarmState")
                        .HasColumnType("boolean")
                        .HasColumnName("alarm_state");

                    b.Property<int>("BaselineSampleCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3)
                        .HasColumnName("baseline_sample_count");

                    b.Property<int>("CalculationMethod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("calculation_method");

                    b.Property<int>("DecimalPlaces")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2)
                        .HasColumnName("decimal_places");

                    b.Property<double>("HighRateHysteresis")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.90000000000000002)
                        .HasColumnName("high_rate_hysteresis");

                    b.Property<double?>("HighRateThreshold")
                        .HasColumnType("double precision")
                        .HasColumnName("high_rate_threshold");

                    b.Property<Guid>("InputItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("input_item_id");

                    b.Property<int>("Interval")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10)
                        .HasColumnName("interval");

                    b.Property<bool>("IsDisabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_disabled");

                    b.Property<double?>("LastInputValue")
                        .HasColumnType("double precision")
                        .HasColumnName("last_input_value");

                    b.Property<double?>("LastSmoothedRate")
                        .HasColumnType("double precision")
                        .HasColumnName("last_smoothed_rate");

                    b.Property<long?>("LastTimestamp")
                        .HasColumnType("bigint")
                        .HasColumnName("last_timestamp");

                    b.Property<double>("LowRateHysteresis")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.90000000000000002)
                        .HasColumnName("low_rate_hysteresis");

                    b.Property<double?>("LowRateThreshold")
                        .HasColumnType("double precision")
                        .HasColumnName("low_rate_threshold");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OutputItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("output_item_id");

                    b.Property<string>("RateUnitDisplay")
                        .HasColumnType("text")
                        .HasColumnName("rate_unit_display");

                    b.Property<double>("SmoothingFilterAlpha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.20000000000000001)
                        .HasColumnName("smoothing_filter_alpha");

                    b.Property<int>("TimeUnit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(60)
                        .HasColumnName("time_unit");

                    b.Property<int>("TimeWindowSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(60)
                        .HasColumnName("time_window_seconds");

                    b.HasKey("Id");

                    b.ToTable("rate_of_change_memory");
                });

            modelBuilder.Entity("Core.Models.RateOfChangeSample", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("RateOfChangeMemoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("rate_of_change_memory_id");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint")
                        .HasColumnName("timestamp");

                    b.Property<double>("Value")
                        .HasColumnType("double precision")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("RateOfChangeMemoryId", "Timestamp");

                    b.ToTable("rate_of_change_sample");
                });

            modelBuilder.Entity("Core.Models.RawItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<long>("Time")
                        .HasColumnType("bigint")
                        .HasColumnName("time");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.ToTable("raw_items");
                });

            modelBuilder.Entity("Core.Models.ScheduleBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<double?>("AnalogOutputValue")
                        .HasColumnType("double precision")
                        .HasColumnName("analog_output_value");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_week");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool?>("DigitalOutputValue")
                        .HasColumnType("boolean")
                        .HasColumnName("digital_output_value");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval")
                        .HasColumnName("end_time");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2)
                        .HasColumnName("priority");

                    b.Property<Guid>("ScheduleMemoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_memory_id");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval")
                        .HasColumnName("start_time");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleMemoryId", "DayOfWeek", "StartTime");

                    b.ToTable("schedule_block");
                });

            modelBuilder.Entity("Core.Models.ScheduleMemory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<double?>("DefaultAnalogValue")
                        .HasColumnType("double precision")
                        .HasColumnName("default_analog_value");

                    b.Property<bool?>("DefaultDigitalValue")
                        .HasColumnType("boolean")
                        .HasColumnName("default_digital_value");

                    b.Property<Guid?>("HolidayCalendarId")
                        .HasColumnType("uuid")
                        .HasColumnName("holiday_calendar_id");

                    b.Property<int>("Interval")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10)
                        .HasColumnName("interval");

                    b.Property<bool>("IsDisabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_disabled");

                    b.Property<Guid?>("LastActiveBlockId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_active_block_id");

                    b.Property<bool>("ManualOverrideActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("manual_override_active");

                    b.Property<double?>("ManualOverrideAnalogValue")
                        .HasColumnType("double precision")
                        .HasColumnName("manual_override_analog_value");

                    b.Property<bool?>("ManualOverrideDigitalValue")
                        .HasColumnType("boolean")
                        .HasColumnName("manual_override_digital_value");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OutputItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("output_item_id");

                    b.Property<DateTime?>("OverrideActivationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("override_activation_time");

                    b.Property<int>("OverrideDurationMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(60)
                        .HasColumnName("override_duration_minutes");

                    b.Property<int>("OverrideExpirationMode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("override_expiration_mode");

                    b.HasKey("Id");

                    b.HasIndex("HolidayCalendarId");

                    b.ToTable("schedule_memory");
                });

            modelBuilder.Entity("Core.Models.StatisticalMemory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("CurrentBatchCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("current_batch_count");

                    b.Property<Guid>("InputItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("input_item_id");

                    b.Property<int>("Interval")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10)
                        .HasColumnName("interval");

                    b.Property<bool>("IsDisabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_disabled");

                    b.Property<long?>("LastResetTime")
                        .HasColumnType("bigint")
                        .HasColumnName("last_reset_time");

                    b.Property<int>("MinSamples")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2)
                        .HasColumnName("min_samples");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("OutputAvgItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("output_avg_item_id");

                    b.Property<Guid?>("OutputCVItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("output_cv_item_id");

                    b.Property<Guid?>("OutputMaxItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("output_max_item_id");

                    b.Property<Guid?>("OutputMedianItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("output_median_item_id");

                    b.Property<Guid?>("OutputMinItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("output_min_item_id");

                    b.Property<Guid?>("OutputRangeItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("output_range_item_id");

                    b.Property<Guid?>("OutputStdDevItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("output_stddev_item_id");

                    b.Property<string>("PercentilesConfig")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("percentiles_config");

                    b.Property<int>("WindowSize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(100)
                        .HasColumnName("window_size");

                    b.Property<int>("WindowType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("window_type");

                    b.HasKey("Id");

                    b.ToTable("statistical_memory");
                });

            modelBuilder.Entity("Core.Models.StatisticalMemorySample", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("StatisticalMemoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("statistical_memory_id");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint")
                        .HasColumnName("timestamp");

                    b.Property<double>("Value")
                        .HasColumnType("double precision")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("StatisticalMemoryId", "Timestamp")
                        .IsDescending(false, true);

                    b.ToTable("statistical_memory_sample");
                });

            modelBuilder.Entity("Core.Models.TimeoutMemory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("InputItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("input_item_id");

                    b.Property<Guid>("OutputItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("output_item_id");

                    b.Property<long>("Timeout")
                        .HasColumnType("bigint")
                        .HasColumnName("timeout");

                    b.HasKey("Id");

                    b.ToTable("timeout_memory");
                });

            modelBuilder.Entity("Core.Models.TotalizerMemory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<double>("AccumulatedValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0)
                        .HasColumnName("accumulated_value");

                    b.Property<int>("AccumulationType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("accumulation_type");

                    b.Property<int>("DecimalPlaces")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2)
                        .HasColumnName("decimal_places");

                    b.Property<Guid>("InputItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("input_item_id");

                    b.Property<int>("Interval")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10)
                        .HasColumnName("interval");

                    b.Property<bool>("IsDisabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_disabled");

                    b.Property<bool?>("LastEventState")
                        .HasColumnType("boolean")
                        .HasColumnName("last_event_state");

                    b.Property<double?>("LastInputValue")
                        .HasColumnType("double precision")
                        .HasColumnName("last_input_value");

                    b.Property<DateTime?>("LastResetTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_reset_time");

                    b.Property<bool>("ManualResetEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("manual_reset_enabled");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OutputItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("output_item_id");

                    b.Property<double?>("OverflowThreshold")
                        .HasColumnType("double precision")
                        .HasColumnName("overflow_threshold");

                    b.Property<string>("ResetCron")
                        .HasColumnType("text")
                        .HasColumnName("reset_cron");

                    b.Property<bool>("ResetOnOverflow")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("reset_on_overflow");

                    b.Property<bool>("ScheduledResetEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("scheduled_reset_enabled");

                    b.Property<string>("Units")
                        .HasColumnType("text")
                        .HasColumnName("units");

                    b.HasKey("Id");

                    b.ToTable("totalizer_memory");
                });

            modelBuilder.Entity("Core.Models.WriteItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<long>("DurationSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_s");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<long>("Time")
                        .HasColumnType("bigint")
                        .HasColumnName("time");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("ItemId")
                        .IsUnique();

                    b.ToTable("write_items");
                });

            modelBuilder.Entity("Core.Models.HolidayDate", b =>
                {
                    b.HasOne("Core.Models.HolidayCalendar", "HolidayCalendar")
                        .WithMany("Dates")
                        .HasForeignKey("HolidayCalendarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HolidayCalendar");
                });

            modelBuilder.Entity("Core.Models.ModbusGatewayMapping", b =>
                {
                    b.HasOne("Core.Models.ModbusGatewayConfig", "Gateway")
                        .WithMany("Mappings")
                        .HasForeignKey("GatewayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.MonitoringItem", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gateway");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Core.Models.RateOfChangeSample", b =>
                {
                    b.HasOne("Core.Models.RateOfChangeMemory", "RateOfChangeMemory")
                        .WithMany("Samples")
                        .HasForeignKey("RateOfChangeMemoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RateOfChangeMemory");
                });

            modelBuilder.Entity("Core.Models.ScheduleBlock", b =>
                {
                    b.HasOne("Core.Models.ScheduleMemory", "ScheduleMemory")
                        .WithMany("ScheduleBlocks")
                        .HasForeignKey("ScheduleMemoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScheduleMemory");
                });

            modelBuilder.Entity("Core.Models.ScheduleMemory", b =>
                {
                    b.HasOne("Core.Models.HolidayCalendar", "HolidayCalendar")
                        .WithMany()
                        .HasForeignKey("HolidayCalendarId");

                    b.Navigation("HolidayCalendar");
                });

            modelBuilder.Entity("Core.Models.StatisticalMemorySample", b =>
                {
                    b.HasOne("Core.Models.StatisticalMemory", "StatisticalMemory")
                        .WithMany("Samples")
                        .HasForeignKey("StatisticalMemoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StatisticalMemory");
                });

            modelBuilder.Entity("Core.Models.HolidayCalendar", b =>
                {
                    b.Navigation("Dates");
                });

            modelBuilder.Entity("Core.Models.ModbusGatewayConfig", b =>
                {
                    b.Navigation("Mappings");
                });

            modelBuilder.Entity("Core.Models.RateOfChangeMemory", b =>
                {
                    b.Navigation("Samples");
                });

            modelBuilder.Entity("Core.Models.ScheduleMemory", b =>
                {
                    b.Navigation("ScheduleBlocks");
                });

            modelBuilder.Entity("Core.Models.StatisticalMemory", b =>
                {
                    b.Navigation("Samples");
                });
#pragma warning restore 612, 618
        }
    }
}
