// <auto-generated />
using System;
using Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Core.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250311182923_db0037")]
    partial class db0037
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Models.ActiveAlarm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AlarmId")
                        .HasColumnType("uuid")
                        .HasColumnName("alarm_id");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<long>("Time")
                        .HasColumnType("bigint")
                        .HasColumnName("time");

                    b.HasKey("Id");

                    b.HasIndex("AlarmId");

                    b.HasIndex("ItemId");

                    b.HasIndex("ItemId", "AlarmId");

                    b.ToTable("active_alarms");
                });

            modelBuilder.Entity("Core.Models.Alarm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("AlarmDelay")
                        .HasColumnType("integer")
                        .HasColumnName("alarm_delay");

                    b.Property<int>("AlarmPriority")
                        .HasColumnType("integer")
                        .HasColumnName("alarm_priority");

                    b.Property<int>("AlarmType")
                        .HasColumnType("integer")
                        .HasColumnName("alarm_type");

                    b.Property<int>("CompareType")
                        .HasColumnType("integer")
                        .HasColumnName("compare_type");

                    b.Property<bool?>("HasExternalAlarm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("has_external_alarm");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsDisabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_disabled");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<int?>("Timeout")
                        .HasColumnType("integer")
                        .HasColumnName("timeout");

                    b.Property<string>("Value1")
                        .HasColumnType("text")
                        .HasColumnName("value1");

                    b.Property<string>("Value2")
                        .HasColumnType("text")
                        .HasColumnName("value2");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("alarms");
                });

            modelBuilder.Entity("Core.Models.AlarmHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(0)
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<long>("Time")
                        .HasColumnType("bigint")
                        .HasColumnName("time")
                        .HasColumnOrder(1);

                    b.Property<Guid>("AlarmId")
                        .HasColumnType("uuid")
                        .HasColumnName("alarm_id");

                    b.Property<string>("AlarmLog")
                        .HasColumnType("text")
                        .HasColumnName("alarm_log");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.HasKey("Id", "Time");

                    b.HasIndex("AlarmId");

                    b.HasIndex("ItemId");

                    b.HasIndex("Time");

                    b.HasIndex("ItemId", "Time");

                    b.ToTable("alarm_history");
                });

            modelBuilder.Entity("Core.Models.ControllerBACnet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("DeviceId")
                        .HasColumnType("integer")
                        .HasColumnName("device_id");

                    b.Property<bool?>("IsDisabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_disabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("controller_bacnet");
                });

            modelBuilder.Entity("Core.Models.ControllerSharp7", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("DBAddress")
                        .HasColumnType("integer")
                        .HasColumnName("db_address");

                    b.Property<int>("DBSizeData")
                        .HasColumnType("integer")
                        .HasColumnName("db_size_data");

                    b.Property<int>("DBStartData")
                        .HasColumnType("integer")
                        .HasColumnName("db_start_data");

                    b.Property<int>("DataType")
                        .HasColumnType("integer")
                        .HasColumnName("data_type");

                    b.Property<byte[]>("EncryptedPassword")
                        .HasColumnType("bytea")
                        .HasColumnName("encrypted_password");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<bool?>("IsDisabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_disabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("controller_sharp7");
                });

            modelBuilder.Entity("Core.Models.Dictionary", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.ToTable("dictionary");
                });

            modelBuilder.Entity("Core.Models.ExternalAlarm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AlarmId")
                        .HasColumnType("uuid")
                        .HasColumnName("alarm_id");

                    b.Property<bool>("IsDisabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_disabled");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<bool>("Value")
                        .HasColumnType("boolean")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("AlarmId");

                    b.ToTable("external_alarms");
                });

            modelBuilder.Entity("Core.Models.FinalItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<long>("Time")
                        .HasColumnType("bigint")
                        .HasColumnName("time");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("ItemId")
                        .IsUnique();

                    b.ToTable("final_items");
                });

            modelBuilder.Entity("Core.Models.ItemHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(0)
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<long>("Time")
                        .HasColumnType("bigint")
                        .HasColumnName("time")
                        .HasColumnOrder(1);

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id", "Time");

                    b.HasIndex("ItemId");

                    b.HasIndex("Time");

                    b.HasIndex("ItemId", "Time");

                    b.ToTable("items_history");
                });

            modelBuilder.Entity("Core.Models.JobDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<Guid>("TriggerId")
                        .HasColumnType("uuid")
                        .HasColumnName("trigger_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("TriggerId");

                    b.ToTable("job_details");
                });

            modelBuilder.Entity("Core.Models.MapBACnet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ControllerId")
                        .HasColumnType("uuid")
                        .HasColumnName("controller_id");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<int>("ObjectId")
                        .HasColumnType("integer")
                        .HasColumnName("object_id");

                    b.Property<int>("ObjectType")
                        .HasColumnType("integer")
                        .HasColumnName("object_type");

                    b.Property<int?>("OperationType")
                        .HasColumnType("integer")
                        .HasColumnName("io_operation_type");

                    b.HasKey("Id");

                    b.ToTable("map_bacnet");
                });

            modelBuilder.Entity("Core.Models.MapSharp7", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int?>("Bit")
                        .HasColumnType("integer")
                        .HasColumnName("bit");

                    b.Property<Guid>("ControllerId")
                        .HasColumnType("uuid")
                        .HasColumnName("controller_id");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<int?>("OperationType")
                        .HasColumnType("integer")
                        .HasColumnName("io_operation_type");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.HasKey("Id");

                    b.ToTable("map_sharp7");
                });

            modelBuilder.Entity("Core.Models.MonitoringItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("CalculationMethod")
                        .HasColumnType("integer")
                        .HasColumnName("calculation_method");

                    b.Property<float?>("CalibrationA")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(1f)
                        .HasColumnName("calibration_a");

                    b.Property<float?>("CalibrationB")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(0f)
                        .HasColumnName("calibration_b");

                    b.Property<int>("InterfaceType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("interface_type");

                    b.Property<bool?>("IsCalibrationEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_calibration_enabled");

                    b.Property<bool?>("IsDisabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_disabled");

                    b.Property<bool>("IsEditable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_editable");

                    b.Property<string>("ItemName")
                        .HasColumnType("text")
                        .HasColumnName("item_name");

                    b.Property<int>("ItemType")
                        .HasColumnType("integer")
                        .HasColumnName("item_type");

                    b.Property<float>("NormMax")
                        .HasColumnType("real")
                        .HasColumnName("norm_max");

                    b.Property<float>("NormMin")
                        .HasColumnType("real")
                        .HasColumnName("norm_min");

                    b.Property<int>("NumberOfSamples")
                        .HasColumnType("integer")
                        .HasColumnName("number_of_samples");

                    b.Property<string>("OffText")
                        .HasColumnType("text")
                        .HasColumnName("off_text");

                    b.Property<string>("OnText")
                        .HasColumnType("text")
                        .HasColumnName("on_text");

                    b.Property<int>("PointNumber")
                        .HasColumnType("integer")
                        .HasColumnName("point_number");

                    b.Property<int>("SaveHistoricalInterval")
                        .HasColumnType("integer")
                        .HasColumnName("save_historical_interval");

                    b.Property<int>("SaveInterval")
                        .HasColumnType("integer")
                        .HasColumnName("save_interval");

                    b.Property<int>("SaveOnChange")
                        .HasColumnType("integer")
                        .HasColumnName("save_on_change");

                    b.Property<float>("SaveOnChangeRange")
                        .HasColumnType("real")
                        .HasColumnName("save_on_change_range");

                    b.Property<float>("ScaleMax")
                        .HasColumnType("real")
                        .HasColumnName("scale_max");

                    b.Property<float>("ScaleMin")
                        .HasColumnType("real")
                        .HasColumnName("scale_min");

                    b.Property<int>("ShouldScale")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2)
                        .HasColumnName("should_scale");

                    b.Property<string>("Unit")
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.HasKey("Id");

                    b.HasIndex("PointNumber")
                        .IsUnique();

                    b.ToTable("items");
                });

            modelBuilder.Entity("Core.Models.PIDMemory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<double>("DeadZone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0)
                        .HasColumnName("dead_zone");

                    b.Property<double>("DerivativeFilterAlpha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(1.0)
                        .HasColumnName("derivative_filter_alpha");

                    b.Property<double>("FeedForward")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0)
                        .HasColumnName("feed_forward");

                    b.Property<Guid>("InputItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("input_item_id");

                    b.Property<int>("Interval")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10)
                        .HasColumnName("interval");

                    b.Property<bool>("IsAuto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_auto");

                    b.Property<Guid?>("IsAutoId")
                        .HasColumnType("uuid")
                        .HasColumnName("is_auto_id");

                    b.Property<bool>("IsDisabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_disabled");

                    b.Property<double>("Kd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.050000000000000003)
                        .HasColumnName("kd");

                    b.Property<double>("Ki")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.10000000000000001)
                        .HasColumnName("ki");

                    b.Property<double>("Kp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(1.0)
                        .HasColumnName("kp");

                    b.Property<double?>("ManualValue")
                        .HasColumnType("double precision")
                        .HasColumnName("manual_value");

                    b.Property<Guid?>("ManualValueId")
                        .HasColumnType("uuid")
                        .HasColumnName("manual_value_id");

                    b.Property<double>("MaxOutputSlewRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(100.0)
                        .HasColumnName("max_output_slew_rate");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OutputItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("output_item_id");

                    b.Property<double>("OutputMax")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(100.0)
                        .HasColumnName("output_max");

                    b.Property<double>("OutputMin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0)
                        .HasColumnName("output_min");

                    b.Property<double?>("SetPoint")
                        .HasColumnType("double precision")
                        .HasColumnName("set_point");

                    b.Property<Guid?>("SetPointId")
                        .HasColumnType("uuid")
                        .HasColumnName("set_point_id");

                    b.HasKey("Id");

                    b.ToTable("pid_memory");
                });

            modelBuilder.Entity("Core.Models.RawItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<long>("Time")
                        .HasColumnType("bigint")
                        .HasColumnName("time");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.ToTable("raw_items");
                });

            modelBuilder.Entity("Core.Models.TimeoutMemory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("InputItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("input_item_id");

                    b.Property<Guid>("OutputItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("output_item_id");

                    b.Property<long>("Timeout")
                        .HasColumnType("bigint")
                        .HasColumnName("timeout");

                    b.HasKey("Id");

                    b.ToTable("timeout_memory");
                });

            modelBuilder.Entity("Core.Models.Trigger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("end_time");

                    b.Property<bool>("IsDisabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_disabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("start_time");

                    b.HasKey("Id");

                    b.ToTable("triggers");
                });

            modelBuilder.Entity("Core.Models.WriteItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<long>("Time")
                        .HasColumnType("bigint")
                        .HasColumnName("time");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("ItemId")
                        .IsUnique();

                    b.ToTable("write_items");
                });
#pragma warning restore 612, 618
        }
    }
}
